# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

kind: ConfigMap
metadata:
  name: ledger-db-config
data:
  POSTGRES_DB: ledger-db
  SPRING_DATASOURCE_DATABASE: ledger-db
  SPRING_DATASOURCE_HOST: ledger-db.cluster-xyz.us-east-1.rds.amazonaws.com
  SPRING_DATASOURCE_PORT: "5432"
  SPRING_DATASOURCE_USERNAME: admin
---
apiVersion: v1
kind: Secret
metadata:
  name: rds-db-config
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: replace-me
  POSTGRES_PASSWORD: replace-me
